name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run card-game tests with pytest
        working-directory: ./card-game
        run: PYTHONPATH=./src pytest -v
      - name: Run fountains tests with pytest
        working-directory: ./fountains
        run: PYTHONPATH=./src pytest -v
